Repository GSG-G11/Team1-Portfolio, pull requests merged in 2022-01, with the labels that each got.

#14 2 file structure
  assets/banner.jpg
  index.html
  style.css
Labels: awaiting-review

#11 Writing the content of README
  README.md
Labels: approve

#17 3 nav bar
  assets/logo.png
  index.html
  style.css
Labels: awaiting-review

#19 add our section code (html and css with animation code)
  assets/work1.jpg
  assets/work2.jpg
  index.html
  style.css
Labels: awaiting-review

#21 15 team section
  assets/female.png
  assets/male.png
  index.html
  style.css
Labels: awaiting-review

#22 8 create contact us
  index.html
  style.css
Labels: awaiting-review

#23 add responsive code of navbar
  all.min.css
  index.html
  style.css
  webfonts/fa-brands-400.eot
  webfonts/fa-brands-400.svg
  webfonts/fa-brands-400.ttf
  webfonts/fa-brands-400.woff
  webfonts/fa-brands-400.woff2
  webfonts/fa-regular-400.eot
  webfonts/fa-regular-400.svg
  webfonts/fa-regular-400.ttf
  webfonts/fa-regular-400.woff
  webfonts/fa-regular-400.woff2
  webfonts/fa-solid-900.eot
  webfonts/fa-solid-900.svg
  webfonts/fa-solid-900.ttf
  webfonts/fa-solid-900.woff
  webfonts/fa-solid-900.woff2
Labels: awaiting-review

#24 add responsive code of header
  style.css
Labels: awaiting-review

#25 add responsive code of team section
  style.css
Labels: awaiting-review

#26 Making the our works section responsive
  assets/ourwork1.jpg
  assets/ourwork2.png
  index.html
  style.css
Labels: awaiting-review

#29 add icons to cards
  index.html
  style.css
Labels: awaiting-review

#30 Create footer for desktop and resposive version
  assets/fLogo.png
  index.html
  style.css
Labels: approved

#31 27 cotact us responsive
  index.html
  style.css
Labels: awaiting-review

#33 adding the final touches
  .vscode/settings.json
  index.html
Labels: approved

#35 fix responsive for contact us seciont
  style.css
Labels: awaiting-review

#37 Readiing footer responsive
  .vscode/settings.json
  style.css
Labels: awaiting-review

#43 adding missing attributes for the form
  index.html
Labels: Done

#45 Adding responsive design for screens less than 1200
  style.css
Labels: Done

#46 fix navbar for 1200-1300px screens
  style.css
Labels: Done
